environment:
  secret: JYDaKOFCRY+I3WPpxPmkFg==

install:
  - nuget install secure-file -Version 1.0.31
  - ps: Test-Path C:\projects\logfarm\src\packages\secure-file.1.0.31\tools\secure-file.exe 
  - ps: Test-Path C:\projects\logfarm\src\TestArtifacts\credentials.enc
  - C:\projects\logfarm\src\packages\secure-file.1.0.31\tools\secure-file.exe -decrypt C:\projects\logfarm\src\TestArtifacts\credentials.enc -secret %secret% -out C:\projects\logfarm\src\TestArtifacts\credentials.dec