environment:
  secret: JYDaKOFCRY+I3WPpxPmkFg==

install:
  - nuget install secure-file -Version 1.0.31
  - src\packages\secure-file.1.0.31\tools\secure-file -decrypt src\TestArtifacts\credentials.enc -secret %secret% -out src\TestArtifacts\credentials.dec